### ISSUE TITLE
twistd example wrong?

### ISSUE THREAD

**Issue by teuben** [timstaley/fourpiskytools#5]
The quick and dirty example in the README file claims to run

     twistd -n comet -v --local-ivo=ivo://fpstoolstest/foo#bar --remote=voevent.4pisky.org

but it seems that --remote needs to be replaced by --subscribe.

**Comment by timstaley** [comment]
Hi @teuben ,
Thanks for the report... I am guessing that you've install comet directly from the repo-master branch?

It looks like John has switched to a new api around a year ago, cf
https://github.com/jdswinbank/Comet/commit/55887b2843606f3b2dbeab25c8b0b4ac8a0414cf#diff-2ee53d9b780c4dc33604e0e213946592
but hasn't made a release since then - so the [docs](https://comet.transientskp.org/en/stable/usage/broker.html) and the version installable via `pip` both use the older syntax, still.

I'll keep this issue open as a reminder to add a note in the docs about comet-versions.

**Comment by teuben** [comment]
I did a "pip install comet" indeed.

**Comment by timstaley** [comment]
Hi @teuben ,

I didn't quite follow that - did you do a pip install comet and that fixed it? Or that was your original install method?

For what it's worth, a fresh install from PyPI of comet works fine for me:
```
mkvirtualenv testcomet
#...

pip install comet
# ...

pip show comet
#Name: Comet
#Version: 3.1.0
#Summary: VOEvent Broker
# ...

# Always a good one to try if you're not 100% sure which version you're actually getting:
python -c "import comet; print(comet.__path__)" 
# ['/home/staley/.virtualenvs/testcomet/lib/python3.6/site-packages/comet']

twistd -n comet -v --local-ivo=ivo://fpstoolstest/foo#bar --remote=voevent.4pisky.org
# ... (Runs fine)


```
